[package]
name = "agct"
version = "0.1.0"
edition = "2021"

[lib]
name = "agct"
crate-type = ["cdylib"]

[dependencies]
chainfile = "0.3.0"
directories = "5.0"
omics = { version = "0.2.0", features = ["coordinate"] }
pyo3 = { version = "0.23.3", features = ["abi3-py310"] }
