[package]
name = "chainlifter"
version = "0.1.0"
edition = "2021"

[lib]
name = "chainlifter"
crate-type = ["cdylib"]

[dependencies]
chainfile = "0.2.1"
directories = "5.0"

[dependencies.pyo3]
version = "0.20.2"
features = ["abi3-py38"]
