name: Checks
on: [push, pull_request]
jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: python3 -m pip install ".[dev]"

      - name: Check style
        run: python3 -m ruff check . && ruff format --check .
  rust-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update Rust
        run: rustup update stable && rustup default stable

      - name: Install rustfmt
        run: rustup component add rustfmt

      - run: cargo fmt -- --check
