name: Checks
on: [push, pull_request]
jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: black
        uses: psf/black@stable

      - name: ruff
        uses: chartboost/ruff-action@v1
  rust-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@nightly

      - uses: mbrobbel/rustfmt-check@master
        with:
          mode: review
